stages:
    - build
    - test
    - checkstyle
build:
    stage: build
    image: maven:3.6.3-jdk-11
    script:
        - echo "Running build stage"
        - mvn clean package
test:
    stage: test
    image: maven:3.6.3-jdk-11
    script: 
        - echo "Running test stage"
        - mvn test
checkstyle:
    stage: checkstyle
    image: maven:3.6.3-jdk-11
    script:
        - echo "Running checkstyle stage"
        - mvn checkstyle:check